services:
  id:
    image: ghcr.io/pocket-id/pocket-id:v2.5.0
    restart: unless-stopped
    networks:
      - global_net
    volumes:
      - pocketid-data:/app/data
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.id.entrypoints=https'
      - 'traefik.http.routers.id.service=id'
      - 'traefik.http.services.id.loadbalancer.server.port=1411'
    environment:
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      APP_URL: https://id.${APP_DOMAIN}
      TRUST_PROXY: true

volumes:
  pocketid-data:

networks:
  global_net:
    external: true
