version: '3'

services:
  pass:
    image: vaultwarden/server:1.30.1
    restart: unless-stopped
    networks:
      - global_net
    volumes:
      - ${HOST_PATH}/data:/data
    environment:
      WEBSOCKET_ENABLED: 'true' # Required to use websockets
      SIGNUPS_ALLOWED: 'false' # set to false to disable signups
      ADMIN_TOKEN: ${ADMIN_TOKEN}
    #ports:
    #  - 80:80
    #  - 3012:3012
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.pass.entrypoints=https'
      - 'traefik.http.routers.pass.service=pass'
      - 'traefik.http.services.pass.loadbalancer.server.port=80'

      - 'traefik.http.routers.pass-websocket.entrypoints=https'
      - 'traefik.http.routers.pass-websocket.rule=Host(`pass.thetoto.fr`) && Path(`/notifications/hub`)'
      - 'traefik.http.routers.pass-websocket.service=pass-websocket'
      - 'traefik.http.services.pass-websocket.loadbalancer.server.port=3012'

networks:
  global_net:
    external: true