version: "3.8"

name: immich

services:
  immich:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:v1.120.1
    networks:
      - immich
      - global_net
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    environment:
      TZ: Europe/Paris
      UPLOAD_LOCATION: ${UPLOAD_LOCATION}
      DB_HOSTNAME: ${DB_HOSTNAME}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOSTNAME: ${REDIS_HOSTNAME}
    #ports:
    #  - 2283:2283
    depends_on:
      - redis
      - database
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.immich.entrypoints=https'
      - 'traefik.http.services.immich.loadbalancer.server.port=2283'

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:v1.120.1
    networks:
      - immich
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    restart: unless-stopped

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine
    networks:
      - immich
    restart: unless-stopped

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    networks:
      - immich
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
  model-cache:

networks:
  immich:
  global_net:
    external: true
