# DEPRECATED, see cloud folder

version: "3"

services:
  cloud2:
    restart: unless-stopped
    image: lscr.io/linuxserver/nextcloud:28.0.4
    networks:
      - global_net
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - DOCKER_MODS=linuxserver/mods:nextcloud-mediadc|linuxserver/mods:nextcloud-memories
      - TRUSTED_PROXIES=172.20.0.0/16 # global_net IPAM subnet
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud2.thetoto.fr
    volumes:
      - ${HOST_PATH}/config:/config
      - ${HOST_PATH}/data:/data
      # Additionnal mounts
      #- /mnt/hdd:/hdd
    #ports:
    #  - 80:80
    labels:
      - 'traefik.enable=true'
      - "traefik.http.routers.nextcloud.entrypoints=https"
      - 'traefik.http.services.nextcloud.loadbalancer.server.port=80'
      - "traefik.http.routers.nextcloud.middlewares=https-headers-nextcloud, nextcloud-caldav, nextcloud-wellknown"

      - "traefik.http.middlewares.nextcloud-caldav.redirectregex.permanent=true"
      - "traefik.http.middlewares.nextcloud-caldav.redirectregex.regex=^https://(.*)/.well-known/(?:card|cal)dav"
      - "traefik.http.middlewares.nextcloud-caldav.redirectregex.replacement=https://$${1}/remote.php/dav/"

      - "traefik.http.middlewares.nextcloud-wellknown.replacepathregex.regex=^(/.well-known.*)"
      - "traefik.http.middlewares.nextcloud-wellknown.replacepathregex.replacement=/index.php$${1}"

      - "traefik.http.middlewares.https-headers-nextcloud.headers.framedeny=false"
      - "traefik.http.middlewares.https-headers-nextcloud.headers.STSSeconds=155520011"
      - "traefik.http.middlewares.https-headers-nextcloud.headers.STSIncludeSubdomains=true"
      - "traefik.http.middlewares.https-headers-nextcloud.headers.STSPreload=true"
      - "traefik.http.middlewares.https-headers-nextcloud.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.https-headers-nextcloud.headers.SSLRedirect=true"
      - "traefik.http.middlewares.https-headers-nextcloud.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.https-headers-nextcloud.headers.customFrameOptionsValue=SAMEORIGIN"
      - "traefik.http.middlewares.https-headers-nextcloud.headers.customResponseHeaders.X-Robots-Tag=noindex, nofollow"
      - "traefik.http.middlewares.https-headers-nextcloud.headers.contentSecurityPolicy=frame-ancestors 'self' thetoto.fr *.thetoto.fr"




networks:
  global_net:
    external: true