version: "3"

services:
  cloud:
    restart: unless-stopped
    image: lscr.io/linuxserver/nextcloud:27.1.3
    networks:
      - global_net
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ${HOST_PATH}/config:/config
      - ${HOST_PATH}/data:/data
      # Additionnal mounts
      #- /mnt/hdd:/hdd
    #ports:
    #  - 80:80
    labels:
      - 'traefik.enable=true'
      - "traefik.http.routers.nextcloud.entrypoints=https"
      - 'traefik.http.services.nextcloud.loadbalancer.server.port=80'
      - "traefik.http.routers.nextcloud.middlewares=https-headers, nextcloud-caldav"

      - "traefik.http.middlewares.nextcloud-caldav.redirectregex.permanent=true"
      - "traefik.http.middlewares.nextcloud-caldav.redirectregex.regex=^https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nextcloud-caldav.redirectregex.replacement=https://$${1}/remote.php/dav/"

      - "traefik.http.middlewares.https-headers.headers.framedeny=true"
      - "traefik.http.middlewares.https-headers.headers.STSSeconds=31536000"
      - "traefik.http.middlewares.https-headers.headers.STSIncludeSubdomains=true"
      - "traefik.http.middlewares.https-headers.headers.STSPreload=true"
      - "traefik.http.middlewares.https-headers.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.https-headers.headers.SSLRedirect=true"
      - "traefik.http.middlewares.https-headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.https-headers.headers.customFrameOptionsValue=SAMEORIGIN"

networks:
  global_net:
    external: true