services:
  dockerproxy:
    image: tecnativa/docker-socket-proxy:latest
    restart: unless-stopped
    environment:
      - CONTAINERS=1
    networks:
      - socket_docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  traefik:
    image: traefik:v3.7.0
    container_name: traefik
    restart: unless-stopped
    depends_on:
      - dockerproxy
    volumes:
      - ${HOST_PATH}/acme.json:/acme.json
      - ${HOST_PATH}/data:/data
    networks:
      - global_net
      - socket_docker
    sysctls:
      net.ipv4.ip_unprivileged_port_start: 0
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api.entrypoints=https'
      - 'traefik.http.routers.api.service=api@internal'
      - 'traefik.http.routers.api.middlewares=gate'
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_API_KEY=${CF_API_KEY}
    ports:
      - 80:80
      - 443:443
    command:
      - '--api'

      - '--providers.docker=true'
      - '--providers.docker.exposedByDefault=false'
      - '--providers.docker.network=global_net'
      - '--providers.docker.endpoint=tcp://dockerproxy:2375'
      - '--providers.docker.defaultRule=Host(`{{ index .Labels "com.docker.compose.service"}}.${APP_DOMAIN}`)'

        # Accept connections on :80 but redirect to :443
      - '--entrypoints.http=true'
      - '--entrypoints.http.address=:80'
      - '--entrypoints.http.http.redirections.entrypoint.to=https'
      - '--entrypoints.http.http.redirections.entrypoint.scheme=https'

        # Accept connections on :443
      - '--entrypoints.https=true'
      - '--entrypoints.https.address=:443'
      - '--entrypoints.https.http.tls=true'
      - '--entrypoints.https.http.tls.certResolver=letsencrypt'
      - '--entrypoints.https.http.tls.domains[0].main=${APP_DOMAIN}'
      - '--entrypoints.https.http.tls.domains[0].sans=*.${APP_DOMAIN}'

      - '--certificatesResolvers.letsencrypt.acme.storage=acme.json'
      - '--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare'
      - '--certificatesResolvers.letsencrypt.acme.caserver=https://acme-v02.api.letsencrypt.org/directory'

      - '--log=true'
      - '--log.level=${TRAEFIK_LOG_LEVEL:-INFO}'

      #- '--accesslog.filepath=/data/access.log'

  gate:
    image: ghcr.io/steveiliop56/tinyauth:v5.0.7
    restart: unless-stopped
    networks:
      - global_net
      - socket_docker
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.gate.entrypoints=https'
      - 'traefik.http.routers.gate.service=gate'
      - 'traefik.http.services.gate.loadbalancer.server.port=3000'
      - 'traefik.http.middlewares.gate.forwardauth.address=http://gate:3000/api/auth/traefik'
      - 'traefik.http.middlewares.gate.forwardauth.authResponseHeaders=Remote-User'

      - 'socket-proxy.allow.get=/v1\..*/(version|containers/.*|events.*)|/_ping'
      - 'socket-proxy.allow.head=/_ping'
    environment:
      DOCKER_HOST: tcp://dockerproxy:2375
      TINYAUTH_UI_TITLE: TheToto Gate
      TINYAUTH_APPURL: https://gate.${APP_DOMAIN}
      TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTID: ${GATE_OIDC_CLIENT_ID}
      TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTSECRET: ${GATE_OIDC_CLIENT_SECRET}
      TINYAUTH_OAUTH_PROVIDERS_POCKETID_AUTHURL: https://id.${APP_DOMAIN}/authorize
      TINYAUTH_OAUTH_PROVIDERS_POCKETID_TOKENURL: https://id.${APP_DOMAIN}/api/oidc/token
      TINYAUTH_OAUTH_PROVIDERS_POCKETID_USERINFOURL: https://id.${APP_DOMAIN}/api/oidc/userinfo
      TINYAUTH_OAUTH_PROVIDERS_POCKETID_REDIRECTURL: https://gate.${APP_DOMAIN}/api/oauth/callback/pocketid
      TINYAUTH_OAUTH_PROVIDERS_POCKETID_SCOPES: openid email profile groups
      TINYAUTH_OAUTH_PROVIDERS_POCKETID_NAME: TheToto Auth

networks:
  global_net:
    external: true

  socket_docker:
