version: '3'

services:
  pass:
    image: bitwardenrs/server:alpine
    restart: unless-stopped
    volumes:
      - ./data:/data
    environment:
      WEBSOCKET_ENABLED: 'true' # Required to use websockets
      SIGNUPS_ALLOWED: 'false'   # set to false to disable signups
    expose:
      - 80
      - 3012
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.bitwarden-ui.entrypoints=https'
      - 'traefik.http.services.bitwarden-ui.loadbalancer.server.port=80'

      - 'traefik.http.routers.bitwarden-websocket.rule=Host(`pass.thetoto.fr`) && Path(`/notifications/hub`)'
      - 'traefik.http.routers.bitwarden-websocket.entrypoints=https'
      - 'traefik.http.services.bitwarden-websocket.loadbalancer.server.port=3012'

      - 'com.centurylinklabs.watchtower.enable=true'
networks:
  default:
    external:
      name: global_net
