version: "3.9"

services:
  # A DB for dev inside code-server
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password

  code:
    image: linuxserver/code-server:latest
    restart: unless-stopped
    container_name: code
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      #- PASSWORD=password #optional - behind Authelia
      #- HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=password #optional
      #- SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=code.thetoto.fr #optional
      - VSCODE_PROXY_URI=https://{{port}}.code.thetoto.fr
      - DEFAULT_WORKSPACE=/workspace #optional
      - EXTENSIONS_GALLERY={"serviceUrl":"https://marketplace.visualstudio.com/_apis/public/gallery","cacheUrl":"https://vscode.blob.core.windows.net/gallery/index","itemUrl":"https://marketplace.visualstudio.com/items"}

      - DOCKER_MODS=linuxserver/mods:code-server-nodejs|linuxserver/mods:code-server-python3|linuxserver/mods:universal-package-install
      - INSTALL_PACKAGES=postgresql-client
    volumes:
      - ./config:/config
      - ./workspace:/workspace
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.code.entrypoints=https'
      - 'traefik.http.routers.code.rule=Host(`code.thetoto.fr`) || HostRegexp(`code.thetoto.fr`, `{subhost:[0-9]+}.code.thetoto.fr`)'
      - 'traefik.http.routers.code.middlewares=authelia@docker'

      - 'com.centurylinklabs.watchtower.enable=true'
    expose:
      - 8443

networks:
  default:
    external:
      name: global_net
