version: '3'
services:
  plex:
    container_name: plex
    image: linuxserver/plex:latest
    restart: always
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/config/plex:/config # plex database
      - ${GDRIVE_DIR}:/gdrive # google drive
    expose: # https://support.plex.tv/articles/201543147-what-network-ports-do-i-need-to-allow-through-my-firewall/
      - 32400

networks:
  default:
    external:
      name: openresty_default
