version: '3'

networks:
  default:
    external:
      name: global_net

services:
  status:
    container_name: status
    image: statping/statping:latest
    restart: unless-stopped
    volumes:
      - ./app:/app
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.status.entrypoints=https'

      - 'com.centurylinklabs.watchtower.enable=true'
    expose:
      - 8080
