version: '3'

networks:
  default:
    external:
      name: global_net

services:
  git:
    container_name: gitea
    image: gitea/gitea:latest
    restart: unless-stopped
    environment:
      - USER_UID=1001
      - USER_GID=1001
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.gitea.entrypoints=https'
      - 'traefik.http.services.gitea.loadbalancer.server.port=3000'
    expose:
      - 3000
    ports:
      - "127.0.0.1:2222:22"
        # It need more configuration.
        # See https://docs.gitea.io/en-us/install-with-docker/#ssh-container-passthrough
        # TODO: Try SSH via Treafik reverse proxy ?
