version: '3'
services:
  assistant:
    container_name: homeassistant
    restart: unless-stopped
    image: homeassistant/home-assistant:stable
    volumes:
      - ./config:/config
    environment:
      - TZ=Europe/Paris
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.assistant.entrypoints=https'
    expose:
      - 8123

networks:
  default:
    external:
      name: global_net
