version: '3'
services:
  assistant:
    container_name: homeassistant
    restart: unless-stopped
    image: homeassistant/home-assistant:stable
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.assistant.entrypoints=https'

      - 'com.centurylinklabs.watchtower.enable=true'
    networks:
      - net
    expose:
      - 8123

networks:
  net:
    external:
      name: global_net
