version: "2"

networks:
  net:
    external:
      name: global_net

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    dns:
      - 192.168.0.1 # Set gateway DNS
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    expose:
      - 80
    networks:
      net:
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.pihole.entrypoints=https'
      - 'traefik.http.routers.pihole.middlewares=localOnly@docker'
      - 'traefik.http.services.pihole.loadbalancer.server.port=80'

      - 'com.centurylinklabs.watchtower.enable=true'
    environment:
      TZ: 'Europe/Paris'
      WEBPASSWORD: '' # Disable password (we are behind Authelia)
      VIRTUAL_HOST: 'pihole.thetoto.fr'
      ServerIP: '192.168.0.10' # Local host IP
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    restart: unless-stopped
