version: '3'
services:
  vpn:
    container_name: vpn
    image: ghcr.io/wfg/openvpn-client
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: unless-stopped
    volumes:
      - ./config/vpn:/data/vpn # OpenVPN configuration
    environment:
      - SUBNETS=192.168.0.0/24,192.168.1.0/24
    expose:
      - 8112 # Deluge Web UI on VPN network
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.deluge.rule=Host(`deluge.thetoto.fr`)'
      - 'traefik.http.routers.deluge.entrypoints=https'
      - 'traefik.http.routers.deluge.middlewares=authelia@docker'
      - 'traefik.http.services.deluge.loadbalancer.server.port=8112'

      - 'com.centurylinklabs.watchtower.enable=false'

  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    restart: unless-stopped
    network_mode: service:vpn # run deluge througt the vpn network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOWNLOADS}:/downloads
      - ./config/deluge:/config
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'

  flaresolverr: # For Jackett, set to "http://flaresolverr:8191"
    container_name: flaresolverr
    image: flaresolverr/flaresolverr:latest
    restart: unless-stopped
    expose:
      - 8191
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'

  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:develop
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config/prowlarr:/config
    expose:
      - 9696
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.prowlarr.entrypoints=https'
      - 'traefik.http.routers.prowlarr.middlewares=authelia@docker'

      - 'com.centurylinklabs.watchtower.enable=true'

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - AUTO_UPDATE=true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOWNLOADS}/torrent:/downloads # place where to put .torrent files for manual download
      - ./config/jackett:/config
    expose:
      - 9117
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.jackett.entrypoints=https'
      - 'traefik.http.routers.jackett.middlewares=authelia@docker'

      - 'com.centurylinklabs.watchtower.enable=true'

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/sonarr:/config
      - ${MEDIA}/Series:/tv # tv shows folder
      - ${MEDIA}/AnimatedSeries:/cartoon # cartoon folder
      - ${MEDIA}/Anime:/anime # anime folder
      - ${DOWNLOADS}:/downloads # download folder
    expose:
      - 8989
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.sonarr.entrypoints=https'
      - 'traefik.http.routers.sonarr.middlewares=authelia@docker'

      - 'com.centurylinklabs.watchtower.enable=true'

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/radarr:/config
      - ${MEDIA}/Movies:/movies # movies folder
      - ${MEDIA}/AnimatedMovies:/animated_movies # animated movies folder
      - ${MEDIA}/Ghibli:/ghibli
      - ${MEDIA}/Dreamworks:/dreamworks
      - ${MEDIA}/Disney:/disney
      - ${DOWNLOADS}:/downloads # download folder
    expose:
      - 7878
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.radarr.entrypoints=https'
      - 'traefik.http.routers.radarr.middlewares=authelia@docker'

      - 'com.centurylinklabs.watchtower.enable=true'

#  bazarr:
#    container_name: bazarr
#    image: linuxserver/bazarr:latest
#    restart: unless-stopped
#    environment:
#      - PUID=${PUID}
#      - PGID=${PGID}
#      - TZ=${TZ}
#    volumes:
#      - ./config/bazarr:/config
#      - ${MEDIA}/movies:/movies # movies folder
#      - ${MEDIA/tv:/tv # tv shows folder
#    expose:
#      - 6767
#    labels:
#      - 'traefik.enable=true'
#      - 'traefik.http.routers.bazarr.entrypoints=https'
#      - 'traefik.http.routers.bazarr.middlewares=authelia@docker'
#
#      - 'com.centurylinklabs.watchtower.enable=true'

  overseerr:
    container_name: overseerr
    image: sctx/overseerr:latest
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Paris
    expose:
      - 5055
    volumes:
      - ./config/overseerr:/app/config
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.overseerr.entrypoints=https'

      - 'com.centurylinklabs.watchtower.enable=true'


  # Delete and redirect to overseerr when ready
  ombi:
    container_name: ombi
    image: linuxserver/ombi:latest
    #image: morbz/docker-web-redirect
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    #  - REDIRECT_TARGET=overseerr.thetoto.fr
    volumes:
      - ./config/ombi:/config
    expose:
      - 3579
    #  - 80
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.ombi.entrypoints=https'

  organizr:
    container_name: organizr
    image: organizr/organizr:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config/organizr:/config
    expose:
      - 80
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.media.rule=Host(`media.thetoto.fr`)'
      - 'traefik.http.routers.media.entrypoints=https'

      - 'com.centurylinklabs.watchtower.enable=true'

  tautulli:
    container_name: tautulli
    image: linuxserver/tautulli:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/tautulli:/config
      - ../plex/config/Library/Application Support/Plex Media Server/Logs:/logs
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.tautulli.entrypoints=https'

      - 'com.centurylinklabs.watchtower.enable=true'
    expose:
      - 8181

networks:
  default:
    external:
      name: global_net
