version: '3'

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:10.11.6
    restart: unless-stopped
    networks:
      - global_net
      - jellyfin
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
      - JELLYFIN_PublishedServerUrl=jellyfin.thetoto.fr #optional
    volumes:
      - ${HOST_PATH}/jellyfin:/config
      - ${MEDIA_PATH}:/data/media # media files
      - /dev/shm:/config/cache/transcodes
    devices:
      - /dev/dri:/dev/dri
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.jellyfin.entrypoints=https'
      - 'traefik.http.services.jellyfin.loadbalancer.server.port=8096'

      - 'traefik.http.routers.jellyfin.middlewares=jellyfin-mw'
      - 'traefik.http.middlewares.jellyfin-mw.headers.customResponseHeaders.X-Robots-Tag=noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex'
      - 'traefik.http.middlewares.jellyfin-mw.headers.SSLRedirect=true'
      - 'traefik.http.middlewares.jellyfin-mw.headers.SSLHost=jellyfin.thetoto.fr'
      - 'traefik.http.middlewares.jellyfin-mw.headers.SSLForceHost=true'
      - 'traefik.http.middlewares.jellyfin-mw.headers.STSSeconds=315360000'
      - 'traefik.http.middlewares.jellyfin-mw.headers.STSIncludeSubdomains=true'
      - 'traefik.http.middlewares.jellyfin-mw.headers.STSPreload=true'
      - 'traefik.http.middlewares.jellyfin-mw.headers.forceSTSHeader=true'
      - 'traefik.http.middlewares.jellyfin-mw.headers.frameDeny=true'
      - 'traefik.http.middlewares.jellyfin-mw.headers.contentTypeNosniff=true'
      - 'traefik.http.middlewares.jellyfin-mw.headers.customresponseheaders.X-XSS-PROTECTION=1'
      - "traefik.http.middlewares.jellyfin-mw.headers.customFrameOptionsValue='allow-from https://jellyfin.thetoto.fr'"
    #network_mode: host # DLNA not working with ports
    #ports:
    # - 8096:8096 
    # - 8920:8920 #optional
    # - 7359:7359/udp #optional
    # - 1900:1900/udp #optional

  jellyseerr:
    image: fallenbagel/jellyseerr:2.2.2
    restart: unless-stopped
    networks:
      - global_net
      - jellyfin
      - services
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
    volumes:
      - ${HOST_PATH}/jellyseerr:/app/config
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.jellyseerr.entrypoints=https'
      - 'traefik.http.services.jellyseerr.loadbalancer.server.port=5055'

  jellysearch:
    image: aleksilassila/jellysearch:latest
    restart: unless-stopped
    networks:
      - jellyfin
    environment:
      - JELLYFIN_URL=http://jellyfin:8096
      - JELLYFIN_API_KEY=${JELLYFIN_API_KEY}
    volumes:
      - ${HOST_PATH}/jellysearch:/config
    #ports:
    #  - 8787:8787

  jellystats:
    image: cyfershepard/jellystats:1.1.1
    restart: unless-stopped
    networks:
      - global_net
      - jellyfin
    environment:
      - TZ=${TZ}
      - JWT_SECRET=${JELLYSTATS_JWT_SECRET}
    volumes:
      - ${HOST_PATH}/jellystats:/app/backend/backup-data
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.jellystats.entrypoints=https'
      - 'traefik.http.services.jellystats.loadbalancer.server.port=3000'
      - 'traefik.http.routers.jellystats.middlewares=authentik@docker'
    #ports:
    #  - 3000:3000

  streamystats:
    image: kyrillsen/streamy-stats:latest
    restart: unless-stopped
    networks:
      - jellyfin
    environment:
      - JELLYFIN_URL=http://jellyfin:8096
      - JELLYFIN_API_KEY=${JELLYFIN_API_KEY}
      - TZ=${TZ}
    volumes:
      - ${HOST_PATH}/streamystats:/app/data
    #ports:
    #  - 8080:8080

networks:
  jellyfin:
  global_net:
    external: true
