services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:10.11.6
    restart: unless-stopped
    networks:
      - global_net
      - jellyfin
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
      - JELLYFIN_PublishedServerUrl=jellyfin.thetoto.fr #optional
    volumes:
      - ${HOST_PATH}/jellyfin:/config
      - ${MEDIA_PATH}:/data/media # media files
      - /dev/shm:/config/cache/transcodes
    devices:
      - /dev/dri:/dev/dri
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.jellyfin.entrypoints=https'
      - 'traefik.http.services.jellyfin.loadbalancer.server.port=8096'

      - 'traefik.http.routers.jellyfin.middlewares=jellyfin-mw'
      - 'traefik.http.middlewares.jellyfin-mw.headers.customResponseHeaders.X-Robots-Tag=noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex'
      - 'traefik.http.middlewares.jellyfin-mw.headers.SSLRedirect=true'
      - 'traefik.http.middlewares.jellyfin-mw.headers.SSLHost=jellyfin.thetoto.fr'
      - 'traefik.http.middlewares.jellyfin-mw.headers.SSLForceHost=true'
      - 'traefik.http.middlewares.jellyfin-mw.headers.STSSeconds=315360000'
      - 'traefik.http.middlewares.jellyfin-mw.headers.STSIncludeSubdomains=true'
      - 'traefik.http.middlewares.jellyfin-mw.headers.STSPreload=true'
      - 'traefik.http.middlewares.jellyfin-mw.headers.forceSTSHeader=true'
      - 'traefik.http.middlewares.jellyfin-mw.headers.frameDeny=true'
      - 'traefik.http.middlewares.jellyfin-mw.headers.contentTypeNosniff=true'
      - 'traefik.http.middlewares.jellyfin-mw.headers.customresponseheaders.X-XSS-PROTECTION=1'
      - "traefik.http.middlewares.jellyfin-mw.headers.customFrameOptionsValue='allow-from https://jellyfin.thetoto.fr'"
    #network_mode: host # DLNA not working with ports
    #ports:
    # - 8096:8096 
    # - 8920:8920 #optional
    # - 7359:7359/udp #optional
    # - 1900:1900/udp #optional

  meilisearch:
    image: getmeili/meilisearch:v1.35.0
    restart: unless-stopped
    networks:
      - jellyfin      
    environment:
      MEILI_ENV: production
      MEILI_NO_ANALYTICS: "true"
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
    volumes:
      - ${HOST_PATH}/meilisearch:/meili_data
    #ports:
    #  - 7700:7700

  # sync watch state with plex for now
  watchstate:
    image: ghcr.io/arabcoders/watchstate:v1.0.8
    user: "${UID}:${GID}"
    restart: unless-stopped
    networks:
      - global_net
      - jellyfin
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.watchstate.loadbalancer.server.port=8080'
      - 'traefik.http.routers.watchstate.entrypoints=https'
      - 'traefik.http.routers.watchstate.middlewares=authentik@docker'
    #ports:
    #  - "8080:8080" # The port which the watchstate will listen on.
    volumes:
      - ${HOST_PATH}/watchstate:/config

networks:
  jellyfin:
  global_net:
    external: true



