version: '3'

services:
  plex:
    image: lscr.io/linuxserver/plex:1.40.4
    restart: unless-stopped
    networks:
      - global_net
    environment:
      - PLEX_CLAIM=claim-XXX
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
    volumes:
      - ${HOST_PATH}/plex:/config # plex database
      - ${MEDIA_PATH}:/media # media files
      - /dev/shm:/transcode
    devices:
      - /dev/dri:/dev/dri
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.plex.entrypoints=https'
      - 'traefik.http.services.plex.loadbalancer.server.port=32400'
      - 'traefik.http.routers.plex.middlewares=plex-headers'

      - 'traefik.http.middlewares.plex-headers.headers.SSLRedirect=true'
      - 'traefik.http.middlewares.plex-headers.headers.STSSeconds=315360000'
      - 'traefik.http.middlewares.plex-headers.headers.browserXSSFilter=true'
      - 'traefik.http.middlewares.plex-headers.headers.contentTypeNosniff=true'
      - 'traefik.http.middlewares.plex-headers.headers.forceSTSHeader=true'
      - 'traefik.http.middlewares.plex-headers.headers.SSLHost=thetoto.fr'
      - 'traefik.http.middlewares.plex-headers.headers.STSIncludeSubdomains=true'
      - 'traefik.http.middlewares.plex-headers.headers.STSPreload=true'
      - 'traefik.http.middlewares.plex-headers.headers.sslproxyheaders.X-Forwarded-Proto=https'
      - 'traefik.http.middlewares.plex-headers.headers.frameDeny=true'
    #network_mode: host # DLNA not working with ports. (multicast udp not supported)
    ports: # https://support.plex.tv/articles/201543147-what-network-ports-do-i-need-to-allow-through-my-firewall/
      - 32400:32400 # Plex
      #- 1900:1900/udp # DLNA
      #- 5353:5353/udp
      #- 32410-32414:32410-32414/udp # GDM
      #- 32469:32469 # DLNA

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    restart: unless-stopped
    networks:
      - global_net
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
      - JELLYFIN_PublishedServerUrl=jellyfin.thetoto.fr #optional
    volumes:
      - ${HOST_PATH}/jellyfin:/config
      - ${MEDIA_PATH}:/data/media # media files
    devices:
      - /dev/dri:/dev/dri
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.jellyfin.entrypoints=https'
      - 'traefik.http.services.jellyfin.loadbalancer.server.port=8096'
    #network_mode: host # DLNA not working with ports
    #ports:
    #  - 8096:8096
    #  - 8920:8920 #optional
    #  - 7359:7359/udp #optional
    #  - 1900:1900/udp #optional

networks:
  global_net:
    external: true