version: '3'

services:
  plex:
    image: lscr.io/linuxserver/plex:1.43.0
    restart: unless-stopped
    networks:
      - global_net
      - plex
    environment:
      - PLEX_CLAIM=${PLEX_CLAIM}
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
    volumes:
      - ${HOST_PATH}/plex:/config # plex database
      - ${MEDIA_PATH}:/media # media files
      - /dev/shm:/transcode
    devices:
      - /dev/dri:/dev/dri
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.plex.entrypoints=https'
      - 'traefik.http.services.plex.loadbalancer.server.port=32400'
      - 'traefik.http.routers.plex.middlewares=plex-headers'

      - 'traefik.http.middlewares.plex-headers.headers.SSLRedirect=true'
      - 'traefik.http.middlewares.plex-headers.headers.STSSeconds=315360000'
      - 'traefik.http.middlewares.plex-headers.headers.browserXSSFilter=true'
      - 'traefik.http.middlewares.plex-headers.headers.contentTypeNosniff=true'
      - 'traefik.http.middlewares.plex-headers.headers.forceSTSHeader=true'
      - 'traefik.http.middlewares.plex-headers.headers.SSLHost=plex.thetoto.fr'
      - 'traefik.http.middlewares.plex-headers.headers.STSIncludeSubdomains=true'
      - 'traefik.http.middlewares.plex-headers.headers.STSPreload=true'
      - 'traefik.http.middlewares.plex-headers.headers.sslproxyheaders.X-Forwarded-Proto=https'
      - 'traefik.http.middlewares.plex-headers.headers.frameDeny=true'
    #network_mode: host # DLNA not working with ports. (multicast udp not supported)
    ports: # https://support.plex.tv/articles/201543147-what-network-ports-do-i-need-to-allow-through-my-firewall/
      - 32400:32400 # Plex
      #- 1900:1900/udp # DLNA
      #- 5353:5353/udp
      #- 32410-32414:32410-32414/udp # GDM
      #- 32469:32469 # DLNA

  plexautolanguages:
    image: journeyover/plex-auto-languages:1.4.1
    restart: unless-stopped
    networks:
      - plex
    environment:
      - PLEX_URL=http://plex:32400
      - PLEX_TOKEN=${PLEX_TOKEN}
      - TZ=${TZ}
    volumes:
      - ${HOST_PATH}/plex-auto-languages:/config

  tautulli:
    image: lscr.io/linuxserver/tautulli:2.16.0
    restart: unless-stopped
    networks:
      - global_net
      - plex
      - services
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
    volumes:
      - ${HOST_PATH}/tautulli:/config
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.tautulli.loadbalancer.server.port=8181'
      - 'traefik.http.routers.tautulli.entrypoints=https'
    #ports:
    #  - 8181:8181

  overseerr:
    image: fallenbagel/jellyseerr:preview-seerr
    restart: unless-stopped
    networks:
      - global_net
      - plex
      - services
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
    volumes:
      - ${HOST_PATH}/overseerr:/app/config
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.overseerr.loadbalancer.server.port=5055'
      - 'traefik.http.routers.overseerr.entrypoints=https'
    #ports:
    #  - 5055:5055

networks:
  plex:
  services:
  global_net:
    external: true
