version: '3.3'

networks:
  net:
    driver: bridge
    name: global_net
  socket_docker:

services:
  dockerproxy:
    image: tecnativa/docker-socket-proxy
    restart: unless-stopped
    environment:
      - CONTAINERS=1
    networks:
      - socket_docker
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  traefik:
    image: traefik:v2.5
    container_name: traefik
    restart: unless-stopped
    depends_on:
      - auth
    volumes:
      - ./traefik/acme.json:/acme.json
    networks:
      - net
      - socket_docker
    #user: 1000:1000
    sysctls:
      net.ipv4.ip_unprivileged_port_start: 0
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api.entrypoints=https'
      - 'traefik.http.routers.api.service=api@internal'
      - 'traefik.http.routers.api.middlewares=authelia@docker,error-pages@docker'

      - 'traefik.http.middlewares.localOnly.ipwhitelist.sourcerange=127.0.0.1/32, 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16'

      - 'com.centurylinklabs.watchtower.monitor-only=true'

      - 'traefik.http.middlewares.test-errorpage.errors.status=400-599'
      - 'traefik.http.middlewares.test-errorpage.errors.service=serviceError'
      - 'traefik.http.middlewares.test-errorpage.errors.query=/errors/{status}.html'
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_API_KEY=${CF_API_KEY}
    extra_hosts:
      - host.docker.internal:192.168.1.2 # For net=host containers (local ip)
    ports:
      - 80:80
      - 443:443
    command:
      - '--api'
      - '--pilot.token=${PILOT_KEY}'

      - '--providers.docker=true'
      - '--providers.docker.exposedByDefault=false'
      - '--providers.docker.endpoint=tcp://dockerproxy:2375'
      - '--providers.docker.defaultRule=Host(`{{ index .Labels "com.docker.compose.service"}}.thetoto.fr`)'

        # Accept connections on :80 but redirect to :443
      - '--entrypoints.http=true'
      - '--entrypoints.http.address=:80'
      - '--entrypoints.http.http.redirections.entrypoint.to=https'
      - '--entrypoints.http.http.redirections.entrypoint.scheme=https'

        # Accept connections on :443
      - '--entrypoints.https=true'
      - '--entrypoints.https.address=:443'
      - '--entrypoints.https.http.tls=true'
      - '--entrypoints.https.http.tls.certResolver=letsencrypt'
      - '--entrypoints.https.http.tls.domains[0].main=thetoto.fr'
      - '--entrypoints.https.http.tls.domains[0].sans=*.thetoto.fr'

      - '--certificatesResolvers.letsencrypt.acme.storage=acme.json'
      - '--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare'
        # Staging
      #- '--certificatesResolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory'
      - '--certificatesResolvers.letsencrypt.acme.caserver=https://acme-v02.api.letsencrypt.org/directory'

      - '--log=true'
      #- '--log.level=DEBUG'
      #- '--log.filepath=/var/log/traefik.log'

      - '--metrics.prometheus=true'

  auth:
    image: authelia/authelia:latest
    container_name: authelia
    restart: unless-stopped
    volumes:
      - ./authelia:/config
    networks:
      - net
    user: 1000:1000
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.authelia.entrypoints=https'

      - 'traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://auth.thetoto.fr'
      - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User, Remote-Groups, Remote-Name, Remote-Email'
      - 'traefik.http.middlewares.authelia-basic.forwardauth.address=http://authelia:9091/api/verify?auth=basic'
      - 'traefik.http.middlewares.authelia-basic.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia-basic.forwardauth.authResponseHeaders=Remote-User, Remote-Groups, Remote-Name, Remote-Email'

      - 'com.centurylinklabs.watchtower.enable=true'
    expose:
      - 9091
    environment:
      - AUTHELIA_JWT_SECRET_FILE=/config/secrets/jwt
      - AUTHELIA_SESSION_SECRET_FILE=/config/secrets/session
      - AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY_FILE=/config/secrets/oidc_private
      - AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE=/config/secrets/oidc_hmac
      - TZ=Europe/Paris

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - ./authelia_redis:/data
    networks:
      - net
    user: 1000:1000
    expose:
      - 6379
    environment:
      - TZ=Europe/Paris

  nginxError:
    container_name: nginxError
    image: nginx:latest
    #command: [nginx-debug, '-g', 'daemon off;']
    restart: unless-stopped
    volumes:
      - ./error-pages:/usr/share/nginx/error-pages
      - ./nginx-error-pages.conf:/etc/nginx/conf.d/default.conf
    networks:
      - net
    expose:
      - 80
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.error-router.entrypoints=https'

      - 'traefik.http.routers.error-router.rule=HostRegexp(`{host:.+}`)'
      - 'traefik.http.routers.error-router.priority=1'
      #- 'traefik.http.routers.error-router.middlewares=error-pages'
  
      - 'traefik.http.middlewares.error-pages.errors.status=400-599'
      - 'traefik.http.middlewares.error-pages.errors.service=error-pages-service'
      - 'traefik.http.middlewares.error-pages.errors.query=/{status}.html'

      - 'traefik.http.services.error-pages-service.loadbalancer.server.port=80'
