version: "3"

services:
  cloud:
    container_name: cloud
    restart: unless-stopped
    image: linuxserver/nextcloud:latest
    #custom build to add dlib for face recognition app
    #build: .
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./config:/config
      - ./data:/data
      - /mnt/hdd:/hdd
      - /mnt/storage:/storage
    labels:
      - 'traefik.enable=true'
      - "traefik.http.routers.nextcloud.entrypoints=https"
      - "traefik.http.routers.nextcloud.middlewares=https-headers, nextcloud-caldav"

      - "traefik.http.middlewares.nextcloud-caldav.redirectregex.permanent=true"
      - "traefik.http.middlewares.nextcloud-caldav.redirectregex.regex=^https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nextcloud-caldav.redirectregex.replacement=https://$${1}/remote.php/dav/"

      - "traefik.http.middlewares.https-headers.headers.framedeny=true"
      - "traefik.http.middlewares.https-headers.headers.STSSeconds=31536000"
      - "traefik.http.middlewares.https-headers.headers.STSIncludeSubdomains=true"
      - "traefik.http.middlewares.https-headers.headers.STSPreload=true"
      - "traefik.http.middlewares.https-headers.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.https-headers.headers.SSLRedirect=true"
      - "traefik.http.middlewares.https-headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.https-headers.headers.customFrameOptionsValue=SAMEORIGIN"

      - 'com.centurylinklabs.watchtower.enable=true'
    expose:
      - 443

networks:
  default:
    external:
      name: global_net
