version: "3"

networks:
  default:
    external:
      name: global_net

services:
  joal:
    image: anthonyraymond/joal
    container_name: joal
    restart: unless-stopped
    volumes:
      - ./data:/data
    expose:
      - 1333
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.joal.entrypoints=https'
      - 'traefik.http.routers.joal.middlewares=authelia@docker'

      - 'com.centurylinklabs.watchtower.enable=false'
    command: ["--joal-conf=/data", "--spring.main.web-environment=true", "--server.port=1333", "--joal.ui.path.prefix=${PATH_PREFIX}", "--joal.ui.secret-token=${SECRET_TOKEN}"]


