version: '3'

services:
  dokku:
    container_name: dokku
    image: dokku/dokku:latest
    restart: unless-stopped
    environment:
      - DOKKU_HOSTNAME=thetoto.fr
    volumes:
      - ${DOKKU_DIR}/mnt:/mnt/dokku
      - ${DOKKU_DIR}/services:/var/lib/dokku/services
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - networks=bridge
    expose:
      - 80
    ports:
      - "7022:22"
        # Almost the same as gitea for ssh config
        # https://docs.gitea.io/en-us/install-with-docker/#ssh-container-passthrough

  # https://github.com/docker/compose/issues/3012 Workaround here
  # We need docker default bridge network for Dokku + openresty (nginx) network
  connect-bridge:
    image: docker:stable
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - dokku
    command: /bin/sh -c "docker ps -f label=networks=bridge -q | xargs -I'{}' docker network connect bridge {}"

networks:
  default:
    external:
      name: openresty_default
