services:
  cloudflared:
    image: cloudflare/cloudflared:2026.5.0
    restart: unless-stopped
    command: tunnel run
    networks:
      - cloudflare
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}

networks: 
  cloudflare:
    external: true
