version: '3.8'

services:
  openresty:
    build: .
    restart: always
    environment:
      - OID_SESSION_SECRET=${OID_SESSION_SECRET}
      - OID_SESSION_CHECK_SSI=off
      - OID_SESSION_NAME=${OID_SESSION_NAME}

      - OID_DISCOVERY=${OID_DISCOVERY}
      - OID_CLIENT_ID=${OID_CLIENT_ID}
      - OID_CLIENT_SECRET=${OID_CLIENT_SECRET}
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
      - ./lua:/usr/local/openresty/nginx/lua
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ${HTML_DIR}:/html
      - ${GDRIVE_DIR}:/mnt/gdrive
      - ./logs:/logs
    ports:
      - 443:443
