version: '3.5'

services:
  photo:
    image: photoprism/photoprism:latest
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    expose:
      - 2342
    restart: unless-stopped
    environment: # Run "photoprism help" and "photoprism config" too see all config options and current values
      # PHOTOPRISM_ADMIN_PASSWORD: "insecure"        # PLEASE CHANGE: This is your initial admin password
      PHOTOPRISM_DEBUG: "false"                      # Run in debug mode (shows additional log messages)
      PHOTOPRISM_PUBLIC: "true"                      # No authentication required (disables password protection) # Behind Authelia
      PHOTOPRISM_READONLY: "false"                   # Don't modify originals directory (reduced functionality)
      PHOTOPRISM_EXPERIMENTAL: "true"                # Enable experimental features
      PHOTOPRISM_SITE_URL: "https://photo.thetoto.fr/"  # Canonical / public site URL
      PHOTOPRISM_SITE_TITLE: "TheToto Photos"
      PHOTOPRISM_SITE_CAPTION: "Save my life"
      PHOTOPRISM_SITE_DESCRIPTION: "An open source Google Photos alternative"
      PHOTOPRISM_SITE_AUTHOR: "TheToto"
      PHOTOPRISM_HTTP_HOST: "0.0.0.0"
      PHOTOPRISM_HTTP_PORT: 2342
      PHOTOPRISM_DISABLE_BACKUPS: "false"            # Don't backup photo and album metadata to YAML files
      PHOTOPRISM_DISABLE_WEBDAV: "true"              # Disable built-in WebDAV server
      PHOTOPRISM_DISABLE_SETTINGS: "false"           # Users can not view or change settings
      PHOTOPRISM_DISABLE_PLACES: "false"             # Disables reverse geocoding and maps
      PHOTOPRISM_DISABLE_EXIFTOOL: "false"           # Don't create ExifTool JSON files for improved metadata extraction
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"         # Don't use TensorFlow for image classification
      PHOTOPRISM_DETECT_NSFW: "false"                # Flag photos as private that MAY be offensive (requires TensorFlow)
      PHOTOPRISM_UPLOAD_NSFW: "true"                 # Allow uploads that MAY be offensive
      PHOTOPRISM_DARKTABLE_PRESETS: "false"          # Use Darktable presets (disables concurrent raw image conversion)
      PHOTOPRISM_DATABASE_DRIVER: "sqlite"           # SQLite is an embedded database that doesn't require a server
      PHOTOPRISM_THUMB_FILTER: "lanczos"             # Resample filter, best to worst: blackman, lanczos, cubic, linear
      PHOTOPRISM_THUMB_UNCACHED: "false"             # Enable on-demand thumbnail rendering (high memory and cpu usage)
      PHOTOPRISM_THUMB_SIZE: 2048                    # Pre-rendered thumbnail size limit (default 2048, min 720, max 7680)
      # PHOTOPRISM_THUMB_SIZE: 4096                  # Retina 4K, DCI 4K (requires more storage); 7680 for 8K Ultra HD
      PHOTOPRISM_THUMB_SIZE_UNCACHED: 7680           # On-demand rendering size limit (default 7680, min 720, max 7680)
      PHOTOPRISM_JPEG_SIZE: 7680                     # Size limit for converted image files in pixels (720-30000)
      PHOTOPRISM_JPEG_QUALITY: 92                    # Set to 95 for high-quality thumbnails (25-100)
    user: "1000:1000"
    volumes:
      # Storage folder for settings, index & sidecar files (DON'T REMOVE):
      - "./photoprism:/photoprism/storage"
      # Your personal photo and video collection ([local path]:[container path]):
      - "/mnt/storage/photos:/photoprism/originals"
      # Multiple folders can be indexed by mounting them as subfolders of /photoprism/originals:
      # - "~/Family:/photoprism/originals/Family"    # [folder_1]:/photoprism/originals/[folder_1]
      # - "~/Friends:/photoprism/originals/Friends"  # [folder_2]:/photoprism/originals/[folder_2]
      # Mounting the import folder is optional (see docs):
      - "/mnt/storage/photos_import:/photoprism/import"
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.photoprism.entrypoints=https'
      - 'traefik.http.routers.photoprism.middlewares=localOnly@docker'
      - 'traefik.http.routers.photoprism.middlewares=authelia@docker'

      - 'com.centurylinklabs.watchtower.enable=true'

networks:
  default:
    external:
      name: global_net
