version: '3'

services:
  prometheus:
    user: 1000:1000
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    expose:
      - 9090
    volumes:
      - ./prometheus_data:/prometheus/
      - ./prometheus/:/etc/prometheus/
#      - ./alertmanager/alert.rules/alerts.rules.yml:/alertmanager/alert.rules/alerts.rules.yml
    command:
      - '--config.file=/etc/prometheus/config.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=365d'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.prometheus.entrypoints=https'
      - 'traefik.http.routers.prometheus.middlewares=authelia@docker'

      - 'com.centurylinklabs.watchtower.enable=true'

#  alertmanager:
#    image: prom/alertmanager:latest
#    container_name: alertmanager
#    restart: unless-stopped
#    expose:
#      - 9093
#    volumes:
#      - ./alertmanager/:/etc/alertmanager/
#    command:
#      - '--config.file=/etc/alertmanager/config.yml'

  grafana:
    user: 1000:1000
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    expose:
      - 3000
    environment:
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel
    depends_on:
      - prometheus
    volumes:
      - ./grafana_data/:/var/lib/grafana/
      - ./grafana/:/etc/grafana/
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.grafana.entrypoints=https'

      - 'com.centurylinklabs.watchtower.enable=true'

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    expose:
      - 9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points'
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"

networks:
  default:
    external:
      name: global_net
